apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: jhipster-poc
spec:
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
      name: http
    - port: 9443
      targetPort: 9443
      protocol: TCP
      name: https
    - port: 9990
      targetPort: 9990
      protocol: TCP
      name: management
  selector:
    app: keycloak