apiVersion: v1
kind: Service
metadata:
  name: firstmicroservice
  namespace: jhipster-poc
  labels:
    app: firstmicroservice
spec:
  selector:
    app: firstmicroservice
  ports:
    - name: http
      port: 8081
