#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to Consul running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MDk3MzUxYTc0OWMwMTIyYTc4MTBmY2RlZjE2OTI0YTE1NzRlNTlkNTUzNzg4MDE1ODY3NzA5NjM3NzhlYzA4MjVlMjE5NDViZWM4NGJjNDU5ZTdiNGEyY2JhOWRhY2I5ZDc5ZQ==
