apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: jhipster-poc
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name: Consul
      status: Connected to Consul running in Kubernetes
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: MzU1N2M2NzM5MjBkYTUyOGE1OGU3YTIyMGNjZmY1MDcyODkyN2IzYmU3NWQ3ZTVhOGQwYWEwMGQ4YmRkMDQ3NDY0ODcwNjMyNzYxMTBkMDQ5ODI0OTA5ZmJmNDE1YTQ2MDE4Mw==
  # app specific configuration
