commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: jhipster-poc

resources:
  - namespace.yml
  # Individual apps
  - firstmicroservice-k8s/firstmicroservice-deployment.yml
  - firstmicroservice-k8s/firstmicroservice-service.yml
  - gateway-k8s/gateway-deployment.yml
  - gateway-k8s/gateway-service.yml
  - secondmicroservice-k8s/secondmicroservice-deployment.yml
  - secondmicroservice-k8s/secondmicroservice-service.yml
  # service discovery eureka/consul
  - registry-k8s/consul.yml
  - registry-k8s/consul-config-loader.yml
  - registry-k8s/application-configmap.yml
  # keycloak
  - keycloak-k8s/keycloak-deployment.yml
  - keycloak-k8s/keycloak-service.yml

patchesJson6902:
